brownplt/captain-teach/web/config/routes.rb
App::Application.routes.draw do
  root 'static#index'

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  post 'review/save/:rid'   => 'review#save'
  get  'review/lookup/:rid' => 'review#lookup'

  get  'resource/lookup'        => 'resource#lookup'
  post 'resource/lookup_create' => 'resource#lookup_create'
  post 'resource/save'          => 'resource#save'
  get  'resource/versions'      => 'resource#versions'
  post 'resource/submit'        => 'resource#submit'

  post 'notification/report_abuse' => 'notification#report_abuse'

  get 'assignment/:uid' => 'assignment#get_assignment', as: :assignment
  get 'grade/:uid/:user_id' => 'assignment#grade_assignment', as: :grade_assignment
  get 'assignment/:uid/edit' => 'assignment#edit_assignment', as: :edit_assignment
  post 'assignment/:uid/edit' => 'assignment#update_assignment', as: :update_assignment

  resource :editor
  get 'editors' => 'editors#index', as: :editors
  post 'editor/:uid/switch' => 'editors#switch_version', as: :editor_switch

  resources :submitted
  get 'submitted/:id/set_good' => 'submitted#good', :as => :submitted_good
  get 'submitted/:id/set_bad' => 'submitted#bad', :as => :submitted_bad
  get 'submitted/:id/set_unknown' => 'submitted#unknown', :as => :submitted_unknown

  resources :user
  post 'user/set_send_email' => 'user#set_send_email', :as => :set_send_email
  get 'user/:id/make_staff' => 'user#make_staff', :as => :make_staff
  get 'user/:id/unmake_staff' => 'user#unmake_staff', :as => :unmake_staff

  resources :course
  post 'course/:id/add_teacher' => 'course#add_teacher', as: :add_teacher
  post 'course/:id/add_student' => 'course#add_student', as: :add_student
  get 'course/:id/show_abuses' => 'course#show_abuses'


  # These all have various security or other concerns for running
  # in production, but are very handy when developing
  if Rails.env.development? or Rails.env.test?
    mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

    get 'assignments' => 'test#all_assignments'

    get 'begin_masquerade' => 'test#masquerade'
    get 'end_masquerade' => 'test#end_masquerade'

    post 'become_user/:uid' => "awesome#become_user"
    get 'all_users' => "awesome#all_users"
    get 'all_assignments' => "test#all_assignments"
    get 'fetch_assignments' => "test#fetch_assignments"
    get 'test_assignment' => "test#test_assignment"
    get 'editor_tests' => "test#editor_tests"
    get 'server_tests' => "test#server_tests"
    get 'submit_tests' => "test#submit_tests"
    get 'canned_feedback_test' => "test#canned_feedback_test"
    get ':action' => 'static#:action'
  end
end

brownplt/captain-teach/web/app/models/editor.rb
class Editor < ActiveRecord::Base
  belongs_to :path_ref
  belongs_to :git_ref

  before_create :add_uid

  def current_git_oid()
    if self.git_ref.nil?
      self.path_ref.user_repo.repo.head.target
    else
      self.git_ref.git_oid
    end
  end

  private
  
  def add_uid()
    self.uid = Digest::MD5.hexdigest(UUIDTools::UUID.random_create.to_s)
  end

  
end

brownplt/captain-teach/web/app/controllers/editors_controller.rb
class EditorsController < ApplicationController

  EDITOR_DIR = File.expand_path("../../../../editors", __FILE__)
  EDITOR_USER = {name: "Edward Teach", email: ""}


  def index
    @editors = Editor.all
  end

  def show
    @all_editors = Editor.all
    @editor = Editor.find_by(uid: params[:format])
  end

  def create
    # create first, so we can use the uid
    @editor = Editor.create!
    user_repo = UserRepo.create!(path: EDITOR_DIR)
    path = PathRef.create!(user_repo: user_repo, path: @editor.uid)
    path.create_file("", "editor #{@editor.uid}",EDITOR_USER)
    @editor.path_ref = path
    @editor.save!
    redirect_to editor_path(@editor.uid)
  end

  def update
    @editor = Editor.find_by(uid: params[:format])
    @editor.title = params[:title]
    @editor.path_ref.save_file(params[:code],
                               "editor #{@editor.uid}",
                               EDITOR_USER)
    # put us back on HEAD
    @editor.git_ref = nil
    @editor.save!
    redirect_to editor_path(@editor.uid)
  end

  def switch_version
    @editor = Editor.find_by(uid: params[:uid])
    # TODO(dbp): verify the hash is valid (this should be a
    # verification in GitRef).
    ref = GitRef.create!(user_repo: @editor.path_ref.user_repo,
                         path: @editor.path_ref.path,
                         git_oid: params[:hash])
    @editor.git_ref = ref
    @editor.save!
    redirect_to editor_path(@editor.uid)
  end


end

brownplt/captain-teach/web/app/views/editors/index.html.erb
<%= form_tag(editor_path, method: "post") do %>
 <%= submit_tag("Create New Editor") %>
<% end %>

<ul>
<% @editors.each do |ed| %>
<li>
<%= link_to ed.title, editor_path(ed.uid), "data-no-turbolink" => true %>
</li>
<% end %>
</ul>

brownplt/captain-teach/web/app/views/editors/show.html.erb
<style>
</style>
<pre id="initial-code" style="display: none"><%= if !@editor.git_ref.nil?; @editor.git_ref.contents; else @editor.path_ref.contents end %></pre>
<script type="text/javascript">

  function updateCode() {
  $("input[name='code']").attr("value", window.editor.getValue());
  return true;
  }

jQuery(function () {
  container = jQuery("#editor");
  var codeContainer = jQuery("<div>");
  container.append(codeContainer);

  var repl = $("<div>").addClass("repl");
  repl.css({height: "100%"});

  window.PANEL = createTabPanel($("#REPL"), { maximizable: true,
                                              minimize: "#editor" });
  PANEL.addTab("Interactions", repl, { cannotClose: true });
  window.REPL = repl;
  window.RUN_CODE = makeRepl(repl);

  window.editor = makeEditor(codeContainer,
                           { initial: $("#initial-code").text(),
                             cmOptions: { lineNumbers: true },
                             run: window.RUN_CODE });

});

</script>

<div id="REPL" class="replContainer"></div>


<div id="editor">
<%= form_tag(editor_path, method: "post", style: "display: inline") do %>
 <%= submit_tag("Create New Editor") %>
<% end %> | Editors:
<% @all_editors.each do |ed| %>
<%= link_to ed.title, editor_path(ed.uid), "data-no-turbolink" => true %>
|
<% end %>
<br/><br/>

<%= form_tag(editor_path(@editor.uid), method: "put") do %>
<%= hidden_field_tag(:code, "") %>
<%= label_tag(:title, "Title:") %>
<%= text_field_tag(:title, @editor.title) %>
<%= submit_tag("Save Editor", :onclick => "return updateCode()") %>
<% end %>

<span>Switch Version:</span>
<% @editor.path_ref.versions.each do |commit| %>
<% if commit[:oid] == @editor.current_git_oid %>
<span style="font-weight: bold"><%= commit[:time] %></span>
<% else %>
<%= form_tag(editor_switch_path(@editor.uid), method: "post", style: "display: inline") do %>
<%= hidden_field_tag(:hash, commit[:oid]) %>
<%= submit_tag("#{commit[:time]}") %>
<% end %>
<% end %>
<% end %>

</div>
<%= render "shared/whalesong" %>