brownplt/captain-teach/web/config/routes.rb
App::Application.routes.draw do
  root 'static#index'

  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  post 'review/save/:rid'   => 'review#save'
  get  'review/lookup/:rid' => 'review#lookup'

  get  'resource/lookup'        => 'resource#lookup'
  post 'resource/lookup_create' => 'resource#lookup_create'
  post 'resource/save'          => 'resource#save'
  get  'resource/versions'      => 'resource#versions'
  post 'resource/submit'        => 'resource#submit'

  post 'notification/report_abuse' => 'notification#report_abuse'

  get 'assignment/:uid' => 'assignment#get_assignment', as: :assignment
  get 'grade/:uid/:user_id' => 'assignment#grade_assignment', as: :grade_assignment
  get 'assignment/:uid/edit' => 'assignment#edit_assignment', as: :edit_assignment
  post 'assignment/:uid/edit' => 'assignment#update_assignment', as: :update_assignment

  resource :editor
  get 'editors' => 'editors#index', as: :editors
  post 'editor/:uid/switch' => 'editors#switch_version', as: :editor_switch

  resources :submitted
  get 'submitted/:id/set_good' => 'submitted#good', :as => :submitted_good
  get 'submitted/:id/set_bad' => 'submitted#bad', :as => :submitted_bad
  get 'submitted/:id/set_unknown' => 'submitted#unknown', :as => :submitted_unknown

  resources :user
  post 'user/set_send_email' => 'user#set_send_email', :as => :set_send_email
  get 'user/:id/make_staff' => 'user#make_staff', :as => :make_staff
  get 'user/:id/unmake_staff' => 'user#unmake_staff', :as => :unmake_staff

  resources :course
  post 'course/:id/add_teacher' => 'course#add_teacher', as: :add_teacher
  post 'course/:id/add_student' => 'course#add_student', as: :add_student
  get 'course/:id/show_abuses' => 'course#show_abuses'


  # These all have various security or other concerns for running
  # in production, but are very handy when developing
  if Rails.env.development? or Rails.env.test?
    mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

    get 'assignments' => 'test#all_assignments'

    get 'begin_masquerade' => 'test#masquerade'
    get 'end_masquerade' => 'test#end_masquerade'

    post 'become_user/:uid' => "awesome#become_user"
    get 'all_users' => "awesome#all_users"
    get 'all_assignments' => "test#all_assignments"
    get 'fetch_assignments' => "test#fetch_assignments"
    get 'test_assignment' => "test#test_assignment"
    get 'editor_tests' => "test#editor_tests"
    get 'server_tests' => "test#server_tests"
    get 'submit_tests' => "test#submit_tests"
    get 'canned_feedback_test' => "test#canned_feedback_test"
    get ':action' => 'static#:action'
  end
end

brownplt/captain-teach/web/app/models/course.rb
class Course < ActiveRecord::Base

  has_many :assignments

  has_and_belongs_to_many :teachers,
    :class_name => "User",
    :join_table => "teachers_courses"
  
  has_and_belongs_to_many :students,
    :class_name => "User",
    :join_table => "students_courses"
  
end

brownplt/captain-teach/web/app/controllers/course_controller.rb
class CourseController < ApplicationController

  before_action :lookup_course, :only => [:show,
                                          :edit,
                                          :update,
                                          :destroy,
                                          :add_teacher,
                                          :add_student,
                                          :show_abuses]

  def index
    if current_user
      @user = current_user
      @student_courses = current_user.student_courses
      @teacher_courses = current_user.teacher_courses
    else
      @student_courses = []
      @teacher_courses = []
    end
  end

  def show
    course_require_teacher(@course)
  end

  def new
  end

  def create
    title = params[:title]
    c = Course.create!(:title => title)
    redirect_to course_path(c)
  end

  def edit
    course_require_teacher(@course)
  end

  def update
    course_require_teacher(@course)
  end

  def destroy
    course_require_teacher(@course)
  end

  def add_teacher
    course_require_teacher(@course)
    t = User.find_by(:email => params[:email])
    if t.nil?
      # FIXME(dbp): actually say what went wrong
      application_not_found
    end
    @course.teachers << t
    redirect_to course_path(@course)
  end

  def add_student
    course_require_teacher(@course)
    s = User.find_by(:email => params[:email])
    if s.nil?
      # FIXME(dbp): actually say what went wrong
      application_not_found
    end
    @course.students << s
    redirect_to course_path(@course)
  end

  def show_abuses
    course_require_teacher(@course)
    @abuses = AbuseRecord.all
  end

  def abusive_blob(abuse_record)
    data = JSON.parse(abuse_record.abuse_data)
    if data["resource"]
      if data["type"] == "review"
        type, perm, ref, args, user = Resource::parse(data["resource"])
        blob = Resource::find_blob_for_inbox(user.id, ref)
        blob_data = JSON.parse(blob.data)
        blob_data
      elsif data["type"] == "feedback"
        type, perm, ref, args, user = Resource::parse(data["resource"])
        blob = Resource::find_blob_for_inbox(user.id, ref)
        blob_data = JSON.parse(blob.data)
        blob_data
      end
    else
      false
    end
  end

  def abusive_user(abuse_record)
    data = JSON.parse(abuse_record.abuse_data)
    b = abusive_blob(abuse_record)
    if b
      if data["type"] == "review"
        the_key = b.keys.sort.select { |k|
          b[k] == data["review"]
        }
        User.find_by(:id => the_key[0].to_i)
      elsif data["type"] == "feedback"
        the_key = b.keys.sort.select { |k| 
          b[k] == Resource::lookup_resource(data["review"]["feedback"]).data
        }
        #Resource::lookup_resource(data["review"]["feedback"]).data
        #b
        User.find_by(:id => the_key[0].to_i)
      end
    else
      false
    end
  end

  private


  def lookup_course
    @course = Course.find(params[:id])
  end


end

brownplt/captain-teach/web/app/views/course/index.html.erb
<% if @student_courses.length != 0 %>
  <h3>Courses I'm Taking:</h3>
  <% @student_courses.each do |c| %>
     <div class='course'>
       <h4><%= c.title %></h4>
       <ul>
         <% c.assignments.each do |a| %>
         <% if (a.release and (a.release < Time.now)) %>
         <li><%= link_to a.path_ref.path, assignment_path(a.uid) %></li>
         <% end %>
         <% end %>
       </ul>
     </div>
  <% end %>
<% end %>

<% if @teacher_courses.length != 0 %>
  <h3>Courses I'm Teaching:</h3>
  <% @teacher_courses.each do |c| %>
  <div class='course'>
    <h4><%= link_to c.title, c %></h4>
    <ul>
      <% c.assignments.each do |a| %>
      <li><%= link_to a.path_ref.path, assignment_path(a.uid) %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

brownplt/captain-teach/web/app/views/course/new.html.erb
<%= form_tag course_index_path  do %>
<%= label_tag(:title, "Title:") %>
<%= text_field_tag(:title) %>
<%= submit_tag("Create Course") %>

<% end %>

brownplt/captain-teach/web/app/views/course/show.html.erb
<h2><%= @course.title %></h2>

<h3>Staff</h3>
<ul>
  <% @course.teachers.each do |u| %>
  <li><%= u.email %></li>
  <% end %>
</ul>

<%= form_tag(add_teacher_path) do %>
<%= label_tag(:email, "Email:") %>
<%= text_field_tag(:email) %>
<%= submit_tag("Add Teacher") %>
<% end %>


<h3>Enrollment</h3>
<ul>
  <% @course.students.each do |u| %>
  <li><%= u.email %></li>
  <% end %>
</ul>

<div>
  <button onclick="$(this).next().toggle()">Add From List</button>
  <div style="display: none">
    <% User.all.each do |u| %>
      <% if u.email and (!u.student_courses.exists?(@course)) %>
        <%= form_tag(add_student_path) do %>
        <%= label_tag(:email, u.email) %>
        <%= hidden_field_tag(:email, u.email) %>
        <%= submit_tag("+") %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<%= form_tag(add_student_path) do %>
<%= label_tag(:email, "Email:") %>
<%= text_field_tag(:email) %>
<%= submit_tag("Add Student") %>
<% end %>

<h3>Assignments</h3>
<ul>
  <% @course.assignments.each do |a| %>
  <li><%= link_to a.path_ref.path, edit_assignment_path(a.uid) %> (<%= link_to "view", assignment_path(a.uid) %>)</li>
    <ul>
    <% @course.students.each do |u| %>

      <li><%= link_to "Grade for #{u.email}", :controller => "assignment", :action => "grade_assignment", :uid => a.uid, :user_id => u.id %></li>
    <% end %>
    </ul>
  <% end %>
</ul>

brownplt/captain-teach/web/app/views/course/show_abuses.html.erb
<% @abuses.each do |a| %>
  <h2>Reported by: <%= a.user.email %> at <%= a.created_at.to_s %></h2>
  <% begin %>
    <% data = JSON.parse(a.abuse_data) %>
    <% url = data["url"] %>
    <p>While visiting: <%= url %></p>
    <% likely_assignment_id = url[url.index("assignment/") + 11, url.length] %>
    <% if data["type"] == "review" %>
      <p>Blaming the contents of this review:</p>
      <pre><%= data["review"] %></pre>
    <% else %>
      <p>Blaming the contents of this feedback:</p>
      <pre><%= Resource::lookup_resource(data["review"]["feedback"]).data %></pre>
    <% end %>
    <%= link_to "See in context (link is a best guess, look for step #{data["step"]["name"]})", {:controller => "assignment", :action => "grade_assignment", :uid => likely_assignment_id, :user_id => a.user.id} %>
    <pre><%= controller.abusive_blob(a) %></pre>
    <% u = controller.abusive_user(a) %>
    <% if u %>
      <%= u.to_json %>
    <% else %>
      Culprit not found...
    <% end %>
  <% rescue JSON::ParserError%>
    <%= "No abuse data." %>
  <% end %>
<% end %>